import prismadb from "@/lib/prismadb";

const DEMO_HOTELS = [
  {
    userId: "demo-user-1",
    title: "Luxury Beach Resort",
    description: "5-star beachfront resort with premium amenities and world-class service",
    image: "/Image/roomImg1.png",
    country: "USA",
    state: "Hawaii",
    city: "Honolulu",
    locationDescription: "Stunning ocean views with private beach access",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Ocean View Suite",
        description: "Luxurious suite with private balcony and ocean view",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 25,
        roomPrice: 350,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: true,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/roomImg1.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-2",
    title: "Mountain Peak Hotel",
    description: "Alpine lodge with breathtaking mountain views and adventure activities",
    image: "/Image/roomImg2.png",
    country: "USA",
    state: "Colorado",
    city: "Aspen",
    locationDescription: "Located at 8,000ft elevation with hiking trails nearby",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: false,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: false,
    coffeeShop: true,
    rooms: [
      {
        title: "Mountain View Room",
        description: "Cozy room with fireplace and mountain views",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 1,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 18,
        roomPrice: 220,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: true,
        mountainView: true,
        airCondition: true,
        soundProofed: false,
        image: "/Image/roomImg2.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-3",
    title: "Urban Boutique Hotel",
    description: "Contemporary luxury hotel in the heart of downtown with rooftop bar",
    image: "/Image/roomImg3.png",
    country: "USA",
    state: "New York",
    city: "New York City",
    locationDescription: "Times Square area with easy access to attractions",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: false,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Deluxe City Room",
        description: "Modern room with city skyline views",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 1,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 20,
        roomPrice: 280,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/roomImg3.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-4",
    title: "Tropical Paradise Resort",
    description: "All-inclusive resort with white sand beaches and water sports",
    image: "/Image/roomImg4.png",
    country: "Mexico",
    state: "Quintana Roo",
    city: "Cancun",
    locationDescription: "Caribbean beachfront with coral reef access",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Beach Club Room",
        description: "Direct beach access with private cabana",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 1,
        breakfastPrice: 30,
        roomPrice: 400,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: true,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/roomImg4.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-5",
    title: "European Palace Hotel",
    description: "Historic luxury hotel with classical architecture and elegant rooms",
    image: "/Image/book1.jpg",
    country: "France",
    state: "Île-de-France",
    city: "Paris",
    locationDescription: "Near Eiffel Tower and Louvre Museum",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: false,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: false,
    coffeeShop: true,
    rooms: [
      {
        title: "Royal Suite",
        description: "Grand suite with Eiffel Tower view",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 35,
        roomPrice: 450,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/book1.jpg",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-6",
    title: "Desert Oasis Hotel",
    description: "Luxurious desert resort with spa and Arabian night experiences",
    image: "/Image/book2.jpg",
    country: "United Arab Emirates",
    state: "Dubai",
    city: "Dubai",
    locationDescription: "Near Palm Jumeirah with desert safari access",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Arabian Nights Suite",
        description: "Luxury suite with private pool and desert view",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 1,
        breakfastPrice: 40,
        roomPrice: 500,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/book2.jpg",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-7",
    title: "Lakeside Manor Resort",
    description: "Peaceful lakeside retreat with water activities and scenic views",
    image: "/Image/book3.jpg",
    country: "USA",
    state: "California",
    city: "Lake Tahoe",
    locationDescription: "Private beach and boat dock access",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: false,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: false,
    coffeeShop: true,
    rooms: [
      {
        title: "Waterfront Cottage",
        description: "Cozy cottage with lake view and private dock",
        bedCount: 2,
        guestCount: 4,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 1,
        breakfastPrice: 22,
        roomPrice: 300,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: true,
        mountainView: false,
        airCondition: true,
        soundProofed: false,
        image: "/Image/book3.jpg",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-8",
    title: "Tokyo Modern Tower",
    description: "Ultra-modern luxury hotel with cutting-edge technology and design",
    image: "/Image/book4.jpg",
    country: "Japan",
    state: "Tokyo",
    city: "Tokyo",
    locationDescription: "Shinjuku district with metro access",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: false,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Executive Tower Room",
        description: "Premium room with city views and smart technology",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 1,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 28,
        roomPrice: 320,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/book4.jpg",
        available: true,
      },
    ],
  },
];

async function seed() {
  try {
    console.log("🌱 Starting database seed...");

    for (const hotelData of DEMO_HOTELS) {
      const { rooms, ...hotelInfo } = hotelData;

      // Create hotel
      const hotel = await prismadb.hotel.create({
        data: {
          ...hotelInfo,
          rooms: {
            create: rooms,
          },
        },
        include: {
          rooms: true,
        },
      });

      console.log(`✅ Created hotel: ${hotel.title}`);
    }

    console.log("🎉 Seed completed successfully!");
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  }
}

seed();
