const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const DEMO_HOTELS = [
  {
    userId: "demo-user-1",
    title: "Luxury Beach Resort",
    description: "5-star beachfront resort with premium amenities and world-class service",
    image: "/Image/roomImg1.png",
    country: "USA",
    state: "Hawaii",
    city: "Honolulu",
    locationDescription: "Stunning ocean views with private beach access",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Ocean View Suite",
        description: "Luxurious suite with private balcony and ocean view",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 25,
        roomPrice: 350,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: true,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/roomImg1.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-2",
    title: "Mountain Peak Hotel",
    description: "Alpine luxury hotel with breathtaking mountain views and outdoor activities",
    image: "/Image/roomImg2.png",
    country: "USA",
    state: "Colorado",
    city: "Aspen",
    locationDescription: "High altitude retreat with ski access",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: false,
    freeParking: true,
    bikeRental: false,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Mountain View Room",
        description: "Cozy room with panoramic mountain views",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 1,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 18,
        roomPrice: 220,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: true,
        mountainView: true,
        airCondition: true,
        soundProofed: true,
        image: "/Image/roomImg2.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-3",
    title: "Urban Boutique Hotel",
    description: "Trendy downtown hotel with modern design and city views",
    image: "/Image/roomImg3.png",
    country: "USA",
    state: "New York",
    city: "New York City",
    locationDescription: "Heart of Manhattan with iconic landmarks nearby",
    gym: true,
    spa: false,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: false,
    bikeRental: true,
    freeWifi: true,
    movieNights: false,
    swimmingPool: false,
    coffeeShop: true,
    rooms: [
      {
        title: "City View Deluxe",
        description: "Modern suite with stunning city views",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 1,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 20,
        roomPrice: 280,
        roomService: true,
        TV: true,
        balcony: false,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/roomImg3.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-4",
    title: "Tropical Paradise Resort",
    description: "All-inclusive tropical resort with water sports and white sand beaches",
    image: "/Image/roomImg4.png",
    country: "Mexico",
    state: "Quintana Roo",
    city: "Cancun",
    locationDescription: "Caribbean paradise with crystal clear waters",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Beachfront Bungalow",
        description: "Private bungalow with direct beach access",
        bedCount: 2,
        guestCount: 4,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 1,
        breakfastPrice: 30,
        roomPrice: 400,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: true,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/roomImg4.png",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-5",
    title: "European Palace Hotel",
    description: "Historic luxury hotel in the heart of Paris with classical architecture",
    image: "/Image/book2.jpg",
    country: "France",
    state: "Île-de-France",
    city: "Paris",
    locationDescription: "Steps away from Eiffel Tower and iconic landmarks",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: false,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: false,
    coffeeShop: true,
    rooms: [
      {
        title: "Royal Suite",
        description: "Opulent suite with Eiffel Tower views",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 2,
        kingBed: 1,
        queenBed: 0,
        breakfastPrice: 35,
        roomPrice: 450,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/book2.jpg",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-6",
    title: "Desert Oasis Hotel",
    description: "Ultra-luxury desert hotel with world-class amenities and architecture",
    image: "/Image/book3.jpg",
    country: "United Arab Emirates",
    state: "Dubai",
    city: "Dubai",
    locationDescription: "Iconic luxury destination in the desert",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: true,
    bikeRental: false,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Presidential Suite",
        description: "Pinnacle of luxury with panoramic views",
        bedCount: 2,
        guestCount: 4,
        bathroomCount: 3,
        kingBed: 1,
        queenBed: 1,
        breakfastPrice: 40,
        roomPrice: 500,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/book3.jpg",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-7",
    title: "Lakeside Manor Resort",
    description: "Exclusive resort nestled by pristine Alpine lake with mountain backdrop",
    image: "/Image/book4.jpg",
    country: "USA",
    state: "California",
    city: "Lake Tahoe",
    locationDescription: "Serene lakeside setting with mountain activities",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: true,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Lake View Manor",
        description: "Spacious room with direct lake and mountain views",
        bedCount: 2,
        guestCount: 4,
        bathroomCount: 2,
        kingBed: true,
        queenBed: true,
        breakfastPrice: 22,
        roomPrice: 300,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: true,
        mountainView: true,
        airCondition: true,
        soundProofed: true,
        image: "/Image/book4.jpg",
        available: true,
      },
    ],
  },
  {
    userId: "demo-user-8",
    title: "Tokyo Modern Tower",
    description: "Contemporary skyscraper hotel in vibrant Tokyo with cutting-edge technology",
    image: "/Image/book5.jpg",
    country: "Japan",
    state: "Tokyo",
    city: "Tokyo",
    locationDescription: "Modern luxury in the heart of Shinjuku district",
    gym: true,
    spa: true,
    bar: true,
    laundry: true,
    restaurant: true,
    shopping: true,
    freeParking: false,
    bikeRental: true,
    freeWifi: true,
    movieNights: true,
    swimmingPool: true,
    coffeeShop: true,
    rooms: [
      {
        title: "Tokyo Skyline Suite",
        description: "High-floor suite with cityscape views",
        bedCount: 1,
        guestCount: 2,
        bathroomCount: 1,
        kingBed: true,
        queenBed: false,
        breakfastPrice: 28,
        roomPrice: 320,
        roomService: true,
        TV: true,
        balcony: true,
        freeWifi: true,
        oceanView: false,
        forestView: false,
        mountainView: false,
        airCondition: true,
        soundProofed: true,
        image: "/Image/book5.jpg",
        available: true,
      },
    ],
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  try {
    for (const hotel of DEMO_HOTELS) {
      const { rooms, ...hotelData } = hotel;
      
      const createdHotel = await prisma.hotel.create({
        data: {
          ...hotelData,
          rooms: {
            create: rooms,
          },
        },
      });

      console.log(`✅ Created hotel: ${createdHotel.title}`);
    }

    console.log("🎉 Seeding completed successfully!");
  } catch (error) {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
